asioso_quick_translate_object:
    path:     /asioso_quick_translate_object
    controller: Asioso\QuickTranslateBundle\Controller\ObjectController::translateObjectAction

asioso_quick_translate_document:
    path:     /asioso_quick_translate_document
    controller: Asioso\QuickTranslateBundle\Controller\DocumentController::saveDocumentAction

asioso_quick_translate_brick:
    path:     /asioso_quick_translate_brick
    controller: Asioso\QuickTranslateBundle\Controller\DocumentController::saveBrickAction

asioso_quick_translate_get_document_elements:
    path:     /asioso_quick_translate_get_document_elements
    controller: Asioso\QuickTranslateBundle\Controller\DocumentController::getDocumentElementsAction

asioso_quick_translate_check_if_exists:
    path:     /asioso_quick_translate_check_if_exists
    controller: Asioso\QuickTranslateBundle\Controller\DocumentController::checkIfExistsAction

#asioso_quick_translate_get_auth_key:
#    path:     /asioso_quick_translate_get_auth_key
#    controller: Asioso\QuickTranslateBundle\Controller\DefaultController::getAuthKeyAction

asioso_quick_translate_get_glossaries:
    path: /asioso_quick_translate_get_glossaries
    controller: Asioso\QuickTranslateBundle\Controller\DefaultController::getGlossariesAction

asioso_quick_translate_text:
    path: /asioso_quick_translate_text
    controller: Asioso\QuickTranslateBundle\Controller\DefaultController::translate